version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # Docker akan mengintip ke file .env untuk mencari isinya
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data: